openapi: 3.1.0
info:
  title: cloud-backend
  version: 0.1.0
paths:
  /instance/alive:
    post:
      tags:
      - instance
      summary: Instance will call this endpoint at startup and every 24H
      operationId: ping_alive
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - type: 'null'
              - $ref: '#/components/schemas/InstanceAliveInput'
      responses:
        '200':
          description: Instance alive status recorded
  /instance/assistant/complete:
    post:
      tags:
      - instance
      summary: Calls the LLM model using the provided chat data messages and waits for the result
      operationId: complete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssistantCompletionInput'
        required: true
      responses:
        '200':
          description: Assistant completion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssistantCompletionPayload'
  /instance/assistant/models:
    get:
      tags:
      - instance
      summary: Instance retrives the list of available LLM models
      operationId: get_models
      responses:
        '200':
          description: Assistant models
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssistantModelsPayload'
  /instance/assistant/usage:
    get:
      tags:
      - instance
      summary: Instance retrieves the usage of assistant credits for the user
      operationId: get_usage
      responses:
        '200':
          description: Assistant usage
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssistantUsagePayload'
  /instance/owner:
    get:
      tags:
      - instance
      summary: Instance will retrieve its owner for access control
      operationId: get_owner
      responses:
        '200':
          description: Instance owner
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceOwnerPayload'
  /instance/user/profile:
    get:
      tags:
      - instance
      summary: Instance retrieves the user profile, refreshed every hour unless offline
      operationId: get_profile
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfilePayload'
  /instance/user/session:
    get:
      tags:
      - instance
      summary: Instance retrieves the user session, refreshed every hour unless offline
      operationId: get_session
      responses:
        '200':
          description: User session
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserSessionPayload'
  /instance/user/session/revoke:
    post:
      tags:
      - instance
      summary: Instance revokes the user session on logout
      operationId: revoke_session
      responses:
        '200':
          description: User session revoked
  /instance/workspace:
    get:
      tags:
      - instance
      summary: Instance will retrieve its workspace for access control
      operationId: get_instance_workspace
      responses:
        '200':
          description: Instance workspace
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstanceWorkspacePayload'
  /oauth2/device/authorize:
    post:
      tags:
      - instance
      - api
      summary: Client starts the OAuth2 device authorization flow
      operationId: device_authorize
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DeviceAuthorizeInput'
        required: true
      responses:
        '200':
          description: Created device authorization request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceAuthorizePayload'
  /oauth2/register:
    post:
      tags:
      - instance
      - api
      summary: Clients registers itself
      operationId: register_client
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterClientInput'
        required: true
      responses:
        '201':
          description: Created client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterClientPayload'
  /oauth2/register/{id}:
    put:
      tags:
      - instance
      - api
      summary: Client updates its OAuth2 client when needed (e.g. to request new scopes)
      operationId: update_client
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClientInput'
        required: true
      responses:
        '200':
          description: Updated client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateClientPayload'
  /oauth2/token:
    post:
      tags:
      - instance
      - api
      summary: Client requests OAuth2 tokens
      operationId: token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenInput'
        required: true
      responses:
        '200':
          description: Created token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPayload'
  /releases/latest:
    get:
      tags:
      - instance
      summary: Instance retrieves the latest release links once at startup and every 24h
      operationId: latest_release
      responses:
        '200':
          description: Latest release
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Release'
  /store/packages:
    get:
      tags:
      - instance
      operationId: get_packages
      parameters:
      - name: kind
        in: query
        required: false
        schema:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/PluginPackageKind'
      responses:
        '200':
          description: List all the packages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PackagesPayload'
components:
  schemas:
    AssistantCompletionInput:
      type: object
      required:
      - model
      - messages
      properties:
        messages:
          type: array
          items:
            type: object
            required:
            - role
            - content
            properties:
              content:
                type: string
              role:
                type: string
        model:
          type: string
    AssistantCompletionPayload:
      type: object
      required:
      - model
      - messages
      - usage
      properties:
        messages:
          type: array
          items:
            type: object
            required:
            - role
            - content
            properties:
              content:
                type: string
              role:
                type: string
        model:
          type: string
        usage:
          type: object
          required:
          - balance
          properties:
            balance:
              type: integer
              format: int64
    AssistantModelsPayload:
      type: object
      required:
      - models
      properties:
        models:
          type: array
          items:
            type: object
            required:
            - id
            - name
            - token_credit
            properties:
              id:
                type: string
              name:
                type: string
              token_credit:
                type: integer
                format: int64
    AssistantUsagePayload:
      type: object
      required:
      - balance
      properties:
        balance:
          type: integer
          format: int64
    DeviceAuthorizeInput:
      type: object
      required:
      - client_id
      - client_secret
      - scope
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        scope:
          type: string
    DeviceAuthorizePayload:
      type: object
      required:
      - device_code
      - user_code
      - verification_uri
      - verification_uri_complete
      - expires_in
      - interval
      properties:
        device_code:
          type: string
        expires_in:
          type: integer
          format: int64
          minimum: 0
        interval:
          type: integer
          format: int64
          minimum: 0
        user_code:
          type: string
        verification_uri:
          type: string
        verification_uri_complete:
          type: string
    InstanceAliveInput:
      type: object
      properties:
        os:
          oneOf:
          - type: 'null'
          - type: object
            properties:
              kind:
                type:
                - string
                - 'null'
              name:
                type:
                - string
                - 'null'
              version:
                type:
                - string
                - 'null'
    InstanceOwnerPayload:
      type: object
      required:
      - id
      - kind
      properties:
        id:
          type: string
        kind:
          type: string
    InstanceWorkspacePayload:
      type: object
      required:
      - id
      - name
      - generation
      properties:
        generation:
          type: integer
          format: int64
        id:
          type: string
        name:
          type: string
    PackagePayload:
      type: object
      required:
      - id
      - license
      - version
      - public_key
      - repository
      - archive
      - signature
      - kind
      - downloads
      properties:
        archive:
          type: string
        author:
          oneOf:
          - type: 'null'
          - type: object
            properties:
              email:
                type:
                - string
                - 'null'
              name:
                type:
                - string
                - 'null'
              url:
                type:
                - string
                - 'null'
        description:
          type:
          - string
          - 'null'
        downloads:
          type: integer
          format: int64
          minimum: 0
        id:
          type: string
        kind:
          $ref: '#/components/schemas/PluginPackageKind'
        license:
          type: string
        name:
          type:
          - string
          - 'null'
        public_key:
          type: string
        repository:
          type: string
        signature:
          type: string
        version:
          type: string
    PackagesPayload:
      type: array
      items:
        $ref: '#/components/schemas/PackagePayload'
    PluginPackageKind:
      type: string
      enum:
      - community
      - official
    RegisterClientInput:
      type: object
      required:
      - scope
      - grant_types
      properties:
        grant_types:
          type: array
          items:
            type: string
        instance_registration_key:
          type:
          - string
          - 'null'
        scope:
          type: string
    RegisterClientPayload:
      type: object
      required:
      - client_id
      - client_secret
      - client_id_issued_at
      - client_secret_expires_at
      - grant_types
      - scope
      - token_endpoint_auth_method
      properties:
        client_id:
          type: string
        client_id_issued_at:
          type: integer
          format: int64
        client_secret:
          type: string
        client_secret_expires_at:
          type: integer
          format: int64
        grant_types:
          type: array
          items:
            type: string
        scope:
          type: string
        token_endpoint_auth_method:
          type: string
    Release:
      type: object
      required:
      - id
      - version
      - links
      - released_at
      properties:
        id:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/ReleaseLink'
        released_at:
          type: string
        version:
          type: string
    ReleaseLink:
      type: object
      required:
      - display
      - platform
      - kind
      - link
      - os
      - arch
      properties:
        arch:
          type: string
        display:
          type: string
        format:
          type:
          - string
          - 'null'
        hash:
          type:
          - string
          - 'null'
        kind:
          type: string
        link:
          type: string
        os:
          type: string
        platform:
          type: string
    TokenInput:
      oneOf:
      - type: object
        title: TokenInputDeviceCode
        required:
        - device_code
        - client_id
        - client_secret
        - grant_type
        properties:
          client_id:
            type: string
          client_secret:
            type: string
          device_code:
            type: string
          grant_type:
            type: string
            enum:
            - urn:ietf:params:oauth:grant-type:device_code
      - type: object
        title: TokenInputRefreshToken
        required:
        - refresh_token
        - client_id
        - client_secret
        - grant_type
        properties:
          client_id:
            type: string
          client_secret:
            type: string
          grant_type:
            type: string
            enum:
            - refresh_token
          refresh_token:
            type: string
      - type: object
        title: TokenInputClientCredentials
        required:
        - client_id
        - client_secret
        - grant_type
        properties:
          client_id:
            type: string
          client_secret:
            type: string
          grant_type:
            type: string
            enum:
            - client_credentials
      - type: object
        title: TokenInputAuthorizationCode
        required:
        - code
        - client_id
        - client_secret
        - redirect_uri
        - grant_type
        properties:
          client_id:
            type: string
          client_secret:
            type: string
          code:
            type: string
          grant_type:
            type: string
            enum:
            - authorization_code
          redirect_uri:
            type: string
    TokenPayload:
      type: object
      required:
      - access_token
      - token_type
      - expires_in
      - scope
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
          format: int64
          minimum: 0
        refresh_token:
          type: string
        scope:
          type: string
        token_type:
          type: string
    UpdateClientInput:
      type: object
      required:
      - client_id
      - client_secret
      - scope
      - grant_types
      properties:
        client_id:
          type: string
        client_secret:
          type: string
        grant_types:
          type: array
          items:
            type: string
        scope:
          type: string
    UpdateClientPayload:
      type: object
      required:
      - client_id
      - client_secret
      - client_id_issued_at
      - client_secret_expires_at
      - grant_types
      - scope
      - token_endpoint_auth_method
      properties:
        client_id:
          type: string
        client_id_issued_at:
          type: integer
          format: int64
        client_secret:
          type: string
        client_secret_expires_at:
          type: integer
          format: int64
        grant_types:
          type: array
          items:
            type: string
        scope:
          type: string
        token_endpoint_auth_method:
          type: string
    UserProfilePayload:
      type: object
      required:
      - id
      - identity
      - subscription
      properties:
        id:
          type: string
        identity:
          type: object
          required:
          - name
          - email
          properties:
            email:
              type: string
            name:
              type: string
        subscription:
          type: object
          required:
          - plan
          - entitlements
          properties:
            entitlements:
              type: array
              items:
                type: object
                required:
                - name
                properties:
                  name:
                    type: string
            plan:
              type: object
              required:
              - name
              properties:
                name:
                  type: string
    UserSessionPayload:
      type: object
      required:
      - id
      - client_id
      - user_id
      - workspace_id
      - generation
      - scopes
      - expires_at
      - created_at
      properties:
        client_id:
          type: string
        created_at:
          type: string
          format: date-time
        expires_at:
          type: string
          format: date-time
        generation:
          type: integer
          format: int64
        id:
          type: string
        scopes:
          type: array
          items:
            type: string
        user_id:
          type: string
        workspace_id:
          type: string
  securitySchemes:
    access_token:
      type: http
      scheme: bearer
      description: OAuth 2.0 Access Token
    pat:
      type: http
      scheme: bearer
      bearerFormat: caido_<token>
      description: Personal Access Token (PAT)
