name: Triage Issue
on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Issue number to triage'
        required: true
        type: string

  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Triage Issue
        uses: caido/action-issue-triager@main
        with:
          issue-number: ${{ inputs['issue-number'] || github.event.issue.number }}
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          system-prompt-file: './prompts/triage.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}