name: Triage Issue
on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Issue number to triage'
        required: true
        type: string
 
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Triage Issue
        uses: caido/action-issue-triager
        with:
          issue-number: ${{ inputs['issue-number'] }}
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          system-prompt-file: './prompts/triage.md'